### ISSUE TITLE
Some help needed with starting the mod

### ISSUE THREAD

**Issue by Infixo** [optimus-code/Cities2Modding#2]
Not sure if there is a better way to just ask few questions.
Step 1. I have BepInEx 6. Seems to be installed correctly. I have enabled console, have logs, config file, etc.
Step 2. The link provided has a nuget package only. However, I noticed that there is already package set in the project and it references HarmonyX version 2.10.2 So, I am not sure if anything else is needed here to do?
Step 3. Build. I built the solution with no errors on first try. I only get warning about 2 libs reference conflict MSB3277. Seems like a deeper issue with some Net libs. Still - no errors.
I ran the game the mod is probably not working? I cannot see any effects. I also cannot find any log entries that should be (?) produced with Unity.Debug.Log.

More info. I am using VS2022. After build, it created BepInEx\plugins\ExampleMod folder and put 2 files into it: 0Harmony.dll and ExampleMod.dll.

**Comment by 89pleasure** [comment]
is this still relevant or can be closed? :)

**Comment by Infixo** [comment]
The issue is still relevant to me, but it is not relevant to mod. I was running BepInEx 6 Pre1 back then, and the mod is configured for BE 674. I cannot, however, run 674 on my setup, idk. Anyway, this has nothing to do with the mod itself.
I am closing it.

**Comment by mkspopov** [comment]
> The issue is still relevant to me, but it is not relevant to mod. I was running BepInEx 6 Pre1 back then, and the mod is configured for BE 674. I cannot, however, run 674 on my setup, idk. Anyway, this has nothing to do with the mod itself. I am closing it.

Hi, I have the same issue. Did you manage to run any other mods? I tried another but the same thing. Do you use BepInEx 5 now?

**Comment by 89pleasure** [comment]
I don't remember what was causing this issue or if it has been fixed.
Just out of curiousity, why not using BepInEx5 instead? All mods do have BepInEx5 versions as far as i know.

**Comment by Infixo** [comment]
Now, yes, I am using BepInEx5. 3 weeks ago it was not so obvious that BepInEx5 would be used, there was v6 and first mods were using it.
I tracked down the issue to DoorStop. My game simply refuses to work with DoorStop v4. Idk why. I reinstalled even Windows, to no avail. Tried various versions, installed directly from github, even recompiled it, nope.

**Comment by 89pleasure** [comment]
We had another one with the same issue, but he never was able to get BepInEx6 to work on his computer. But I think he said that the BepInEx6-pre version (not the burning edge version) did work. Dunno if you tried that.

**Comment by Infixo** [comment]
@89pleasure PRE-1 version works ok for me, because it uses previous DoorStop, 3 I think? I checked several BepInEx bleeding edge versions, and there is a big gap in released versions, during which they implemented upgrade for DoorStop. Any BE version after that doesn't work for me.
