### ISSUE TITLE
help for the mod sharing.

### ISSUE THREAD

**Issue by mmcme** [optimus-code/Cities2Modding#4]
hi , 
thanks for your modding guide.
i noitce this example needs:BepInEx 6,HarmonyX.
i have one question :
if i develop a mod which follows your example,and then share this mod to others, do they also need to install BepInEx and HarmonyX?

thanks.

**Comment by optimus-code** [comment]
Hi, this methodology is not really relevant any more as the official code modding tools are available. This method pre-dates official mod support. I'd suggest joining our Discord if you want some help pointing in the right direction!
